In [1]:
import pandas as pd

In [4]:
top = pd.read_csv('top_5_productos_geozona.csv')
top[(top['vendor_id'] == 1303) & ()]

,point_of_sale_id,super_catalog_id,unidades_pedidas,precio_minimo,geo_zone,vendor_id,name,base_price,percentage,precio_vendedor,precio_total_vendedor,status,valor_total_vendedor
1903,1616,7501573900443,127.0,5.10,Estado de México,1303,Estado de México,4.70,0.0,4.70,596.90,NaN,596.90
1904,1616,7502227877722,11.0,57.82,Estado de México,1303,Estado de México,53.03,0.0,53.03,583.33,NaN,583.33
1958,1616,7501825304142,24.0,12.50,Estado de México,1303,Estado de México,10.56,0.0,10.56,253.44,NaN,253.44
1971,1729,7501573905417,15.0,14.35,Estado de México,1303,Estado de México,13.90,0.0,13.90,208.50,1.0,208.50
1975,2277,7503001008684,5.0,42.41,Estado de México,1303,Estado de México,36.60,0.0,36.60,183.00,1.0,183.00
2018,1616,7501258203395,5.0,26.35,Estado de México,1303,Estado de México,24.17,0.0,24.17,120.85,NaN,120.85
2040,1729,7503001007090,5.0,21.59,Estado de México,1303,Estado de México,18.65,0.0,18.65,93.25,1.0,93.25
2139,1616,7502211783657,1.0,71.90,Estado de México,1303,Estado de México,40.53,0.0,40.53,40.53,NaN,40.53
2168,2119,7503001007199,1.0,33.02,Estado de México,1303,Estado de México,29.20,0.0,29.20,29.20,NaN,29.20
2170,1616,7502208892645,1.0,35.59,Estado de México,1303,Estado de México,28.22,0.0,28.22,28.22,NaN,28.22
2184,1616,7502259890096,1.0,26.78,Estado de México,1303,Estado de México,25.09,0.0,25.09,25.09,NaN,25.09
2192,1601,7501048692187,2.0,17.19,Estado de México,1303,Estado de México,11.04,0.0,11.04,22.08,NaN,22.08
2197,2119,7502211783275,1.0,28.73,Estado de México,1303,Estado de México,19.68,0.0,19.68,19.68,NaN,19.68
2212,2119,7501573904755,4.0,38.24,Estado de México,1303,Estado de México,2.10,0.0,2.10,8.40,NaN,8.40

In [11]:
top[(top['name'] == 'CDMX')] #& (top['name']=='CDMX')]

Empty DataFrame
Columns: [point_of_sale_id, super_catalog_id, unidades_pedidas, precio_minimo, geo_zone, vendor_id, name, base_price, percentage, precio_vendedor, precio_total_vendedor, status, valor_total_vendedor]
Index: []

In [8]:
orders = pd.read_csv('orders_delivered_pos_vendor_geozone.csv')
orders[(orders['vendor_id']==10608) & (orders['geo_zone']=='CDMX')]

,point_of_sale_id,super_catalog_id,unidades_pedidas,precio_minimo,vendor_id,geo_zone,country
28225,1794,8400009265,1.0,85.940,10608,CDMX,MX
28239,1794,7501159526029,1.0,288.248,10608,CDMX,MX
28241,1794,7501258203586,3.0,29.550,10608,CDMX,MX
28242,1794,7501258203593,1.0,23.500,10608,CDMX,MX
28244,1794,7501299370360,3.0,32.280,10608,CDMX,MX
28253,1794,7501537102982,2.0,20.000,10608,CDMX,MX
28254,1794,7501537102999,7.0,10.500,10608,CDMX,MX
28258,1794,7501573903260,3.0,14.770,10608,CDMX,MX
28265,1794,7502009741753,1.0,12.140,10608,CDMX,MX
28268,1794,7502211784043,1.0,28.870,10608,CDMX,MX
28277,1794,7503027446279,10.0,22.107,10608,CDMX,MX
28281,1794,821998000250,1.0,41.180,10608,CDMX,MX